-- =========================================
-- ITSM PRO - SCHEMA INICIAL DO SUPABASE
-- =========================================

-- Ativar a extensão para usar UUIDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Tabela de Ativos (Inventário de Hardware)
CREATE TABLE ativos (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  brand TEXT,
  model TEXT,
  mac_address TEXT,
  ip_address TEXT,
  serial_number TEXT,
  location TEXT,
  status TEXT DEFAULT 'Ativo',
  condition TEXT,
  last_maintenance TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabela de Chamados (Helpdesk)
CREATE TABLE chamados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID Numérico para facil visualização (ex: #1042)
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'Aberto',
  requester TEXT NOT NULL,
  department TEXT,
  priority TEXT DEFAULT 'Normal',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  solved_at TIMESTAMP WITH TIME ZONE,
  solution_notes TEXT
);

-- 3. Tabela de Checkout (Empréstimos de Equipamentos)
CREATE TABLE checkout_loans (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  asset_name TEXT NOT NULL,
  asset_tag TEXT,
  borrower_name TEXT NOT NULL,
  borrower_role TEXT,
  department TEXT,
  status TEXT DEFAULT 'Ativo',
  loan_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expected_return_date TIMESTAMP WITH TIME ZONE,
  return_date TIMESTAMP WITH TIME ZONE,
  notes TEXT
);

-- 4. Tabela do Almoxarifado (Insumos)
CREATE TABLE almoxarifado (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  qty INTEGER DEFAULT 0,
  min_qty INTEGER DEFAULT 0,
  unit TEXT DEFAULT 'Und',
  cost NUMERIC(10, 2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Tabela de Movimentações do Almoxarifado (Extrato)
CREATE TABLE almoxarifado_transactions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  item_id UUID REFERENCES almoxarifado(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'in' (entrada) ou 'out' (baixa)
  qty INTEGER NOT NULL,
  user_name TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =========================================
-- DADOS DE EXEMPLO (MOCKS INICIAIS)
-- =========================================

INSERT INTO ativos (name, category, brand, model, mac_address, ip_address, serial_number, location, status, condition, last_maintenance)
VALUES 
('PC-PROD-01', 'Computador', 'Dell', 'Optiplex 3080 Micro', '00:1B:44:11:3A:B7', '192.168.1.105', 'DX100922A', 'Qualidade / Galpão 1', 'Ativo', 'Bom (Uso diário)', '10/Set/2026'),
('SW-CORE-AG-01', 'Switch', 'Cisco', 'Catalyst 9200L', 'CC:46:D6:22:1A:00', '10.0.0.1', 'CX5500-PT', 'Rack Principal - TI', 'Ativo', 'Novo', '01/Out/2026'),
('COL-ZBRA-04', 'Coletor de Dados', 'Zebra', 'TC52', 'A4:BB:6D:99:FF:21', 'DHCP', 'ZBR9992', 'Recebimento', 'Manutenção', 'Marcas de queda', 'Houve falha ontem');

INSERT INTO chamados (title, description, status, requester, department, priority)
VALUES 
('Sistema ERP não abre e apresenta "Network Error"', 'Usuários do setor de faturamento relatam que não conseguem acessar o TOTVS.', 'Crítico', 'Ana Oliveira', 'Faturamento', 'Alta'),
('Adicionar Impressora Térmica na Doca 3', 'O cabo original rompeu, precisamos configurar pelo Wi-Fi.', 'Em Atendimento', 'Marcos Silva', 'Logística', 'Normal'),
('Upgrade de Memória RAM Notebook Gerência', 'O computador da coordenação está travando ao abrir planilhas grandes.', 'Resolvido', 'Carlos Mendes', 'Diretoria', 'Baixa');

INSERT INTO almoxarifado (name, category, qty, min_qty, unit, cost)
VALUES
('Cabo de Rede CAT6 Azul (Caixa 305m)', 'Cabeamento', 2, 1, 'Caixas', 450.00),
('Mouse Óptico USB Dell', 'Periféricos', 15, 5, 'Und', 45.00),
('Toner Preto Zebra Monocromática', 'Impressão', 1, 3, 'Und', 120.00),
('Teclado USB ABNT2', 'Periféricos', 4, 5, 'Und', 65.00);
